# Generated by Django 5.1.3 on 2024-11-11 08:37

import utilmeta.core.orm.backends.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=utilmeta.core.orm.backends.django.models.ACASCADE, related_name='articles', to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=utilmeta.core.orm.backends.django.models.ACASCADE, related_name='comments', to='article.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=utilmeta.core.orm.backends.django.models.ACASCADE, related_name='comments', to='user.user'),
        ),
    ]
