# Generated by Django 4.0.1 on 2022-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
