# Generated by Django 3.2.2 on 2022-02-09 11:58

from django.db import migrations, models
import utilmeta.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', utilmeta.fields.PasswordField(max_length=60, min_length=1, regex=None, salt_length=32)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('token', models.TextField(default=None, null=True)),
                ('bio', models.TextField(default=None, null=True)),
                ('image', models.URLField(default=None, null=True)),
                ('favorites', models.ManyToManyField(related_name='favorited_bys', to='article.Article')),
                ('followers', models.ManyToManyField(related_name='followed_bys', to='user.User')),
            ],
        ),
    ]
